--
-- Webtrees PostgreSQL Schema
-- Generated by dumping from webtrees 2.2.4
--

CREATE DATABASE "<DB_NAME>" WITH ENCODING 'UTF8';
\c "<DB_NAME>"

--
-- PostgreSQL database dump
--


-- Dumped from database version 18.1 (Debian 18.1-1.pgdg13+2)
-- Dumped by pg_dump version 18.1 (Debian 18.1-1.pgdg13+2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

ALTER TABLE IF EXISTS ONLY public.wt_user_setting DROP CONSTRAINT IF EXISTS wt_user_setting_user_id_foreign;
ALTER TABLE IF EXISTS ONLY public.wt_user_gedcom_setting DROP CONSTRAINT IF EXISTS wt_user_gedcom_setting_user_id_foreign;
ALTER TABLE IF EXISTS ONLY public.wt_user_gedcom_setting DROP CONSTRAINT IF EXISTS wt_user_gedcom_setting_gedcom_id_foreign;
ALTER TABLE IF EXISTS ONLY public.wt_place_location DROP CONSTRAINT IF EXISTS wt_place_location_parent_id_foreign;
ALTER TABLE IF EXISTS ONLY public.wt_news DROP CONSTRAINT IF EXISTS wt_news_user_id_foreign;
ALTER TABLE IF EXISTS ONLY public.wt_news DROP CONSTRAINT IF EXISTS wt_news_gedcom_id_foreign;
ALTER TABLE IF EXISTS ONLY public.wt_module_setting DROP CONSTRAINT IF EXISTS wt_module_setting_module_name_foreign;
ALTER TABLE IF EXISTS ONLY public.wt_module_privacy DROP CONSTRAINT IF EXISTS wt_module_privacy_module_name_foreign;
ALTER TABLE IF EXISTS ONLY public.wt_module_privacy DROP CONSTRAINT IF EXISTS wt_module_privacy_gedcom_id_foreign;
ALTER TABLE IF EXISTS ONLY public.wt_message DROP CONSTRAINT IF EXISTS wt_message_user_id_foreign;
ALTER TABLE IF EXISTS ONLY public.wt_log DROP CONSTRAINT IF EXISTS wt_log_user_id_foreign;
ALTER TABLE IF EXISTS ONLY public.wt_log DROP CONSTRAINT IF EXISTS wt_log_gedcom_id_foreign;
ALTER TABLE IF EXISTS ONLY public.wt_hit_counter DROP CONSTRAINT IF EXISTS wt_hit_counter_gedcom_id_foreign;
ALTER TABLE IF EXISTS ONLY public.wt_gedcom_setting DROP CONSTRAINT IF EXISTS wt_gedcom_setting_gedcom_id_foreign;
ALTER TABLE IF EXISTS ONLY public.wt_gedcom_chunk DROP CONSTRAINT IF EXISTS wt_gedcom_chunk_gedcom_id_foreign;
ALTER TABLE IF EXISTS ONLY public.wt_favorite DROP CONSTRAINT IF EXISTS wt_favorite_user_id_foreign;
ALTER TABLE IF EXISTS ONLY public.wt_favorite DROP CONSTRAINT IF EXISTS wt_favorite_gedcom_id_foreign;
ALTER TABLE IF EXISTS ONLY public.wt_default_resn DROP CONSTRAINT IF EXISTS wt_default_resn_gedcom_id_foreign;
ALTER TABLE IF EXISTS ONLY public.wt_change DROP CONSTRAINT IF EXISTS wt_change_user_id_foreign;
ALTER TABLE IF EXISTS ONLY public.wt_change DROP CONSTRAINT IF EXISTS wt_change_gedcom_id_foreign;
ALTER TABLE IF EXISTS ONLY public.wt_block DROP CONSTRAINT IF EXISTS wt_block_user_id_foreign;
ALTER TABLE IF EXISTS ONLY public.wt_block_setting DROP CONSTRAINT IF EXISTS wt_block_setting_block_id_foreign;
ALTER TABLE IF EXISTS ONLY public.wt_block DROP CONSTRAINT IF EXISTS wt_block_module_name_foreign;
ALTER TABLE IF EXISTS ONLY public.wt_block DROP CONSTRAINT IF EXISTS wt_block_gedcom_id_foreign;
DROP INDEX IF EXISTS public.wt_user_gedcom_setting_gedcom_id_index;
DROP INDEX IF EXISTS public.wt_sources_s_name_index;
DROP INDEX IF EXISTS public.wt_session_user_id_ip_address_index;
DROP INDEX IF EXISTS public.wt_session_session_time_index;
DROP INDEX IF EXISTS public.wt_places_p_file_p_place_index;
DROP INDEX IF EXISTS public.wt_placelinks_pl_p_id_index;
DROP INDEX IF EXISTS public.wt_placelinks_pl_gid_index;
DROP INDEX IF EXISTS public.wt_placelinks_pl_file_index;
DROP INDEX IF EXISTS public.wt_place_location_longitude_index;
DROP INDEX IF EXISTS public.wt_place_location_latitude_index;
DROP INDEX IF EXISTS public.wt_news_user_id_updated_index;
DROP INDEX IF EXISTS public.wt_news_gedcom_id_updated_index;
DROP INDEX IF EXISTS public.wt_name_n_surn_n_file_n_type_n_id_index;
DROP INDEX IF EXISTS public.wt_name_n_givn_n_file_n_type_n_id_index;
DROP INDEX IF EXISTS public.wt_name_n_full_n_id_n_file_index;
DROP INDEX IF EXISTS public.wt_message_user_id_index;
DROP INDEX IF EXISTS public.wt_media_file_m_id_m_file_index;
DROP INDEX IF EXISTS public.wt_media_file_m_file_source_media_type_index;
DROP INDEX IF EXISTS public.wt_media_file_m_file_multimedia_format_index;
DROP INDEX IF EXISTS public.wt_media_file_m_file_multimedia_file_refn_index;
DROP INDEX IF EXISTS public.wt_media_file_m_file_m_id_index;
DROP INDEX IF EXISTS public.wt_media_file_m_file_descriptive_title_index;
DROP INDEX IF EXISTS public.wt_log_user_id_index;
DROP INDEX IF EXISTS public.wt_log_log_type_index;
DROP INDEX IF EXISTS public.wt_log_log_time_index;
DROP INDEX IF EXISTS public.wt_log_ip_address_index;
DROP INDEX IF EXISTS public.wt_log_gedcom_id_index;
DROP INDEX IF EXISTS public.wt_gedcom_sort_order_index;
DROP INDEX IF EXISTS public.wt_gedcom_chunk_gedcom_id_imported_index;
DROP INDEX IF EXISTS public.wt_favorite_user_id_index;
DROP INDEX IF EXISTS public.wt_favorite_gedcom_id_user_id_index;
DROP INDEX IF EXISTS public.wt_families_f_wife_index;
DROP INDEX IF EXISTS public.wt_families_f_husb_index;
DROP INDEX IF EXISTS public.wt_dates_d_year_index;
DROP INDEX IF EXISTS public.wt_dates_d_type_index;
DROP INDEX IF EXISTS public.wt_dates_d_month_index;
DROP INDEX IF EXISTS public.wt_dates_d_mon_index;
DROP INDEX IF EXISTS public.wt_dates_d_julianday2_index;
DROP INDEX IF EXISTS public.wt_dates_d_julianday1_index;
DROP INDEX IF EXISTS public.wt_dates_d_gid_index;
DROP INDEX IF EXISTS public.wt_dates_d_file_index;
DROP INDEX IF EXISTS public.wt_dates_d_fact_d_gid_index;
DROP INDEX IF EXISTS public.wt_dates_d_day_index;
DROP INDEX IF EXISTS public.wt_change_user_id_index;
DROP INDEX IF EXISTS public.wt_change_gedcom_id_status_xref_index;
DROP INDEX IF EXISTS public.wt_block_user_id_index;
DROP INDEX IF EXISTS public.wt_block_module_name_index;
DROP INDEX IF EXISTS public.wt_block_gedcom_id_index;
ALTER TABLE IF EXISTS ONLY public.wt_user DROP CONSTRAINT IF EXISTS wt_user_user_name_unique;
ALTER TABLE IF EXISTS ONLY public.wt_user_setting DROP CONSTRAINT IF EXISTS wt_user_setting_pkey;
ALTER TABLE IF EXISTS ONLY public.wt_user DROP CONSTRAINT IF EXISTS wt_user_pkey;
ALTER TABLE IF EXISTS ONLY public.wt_user_gedcom_setting DROP CONSTRAINT IF EXISTS wt_user_gedcom_setting_pkey;
ALTER TABLE IF EXISTS ONLY public.wt_user DROP CONSTRAINT IF EXISTS wt_user_email_unique;
ALTER TABLE IF EXISTS ONLY public.wt_sources DROP CONSTRAINT IF EXISTS wt_sources_s_file_s_id_unique;
ALTER TABLE IF EXISTS ONLY public.wt_sources DROP CONSTRAINT IF EXISTS wt_sources_pkey;
ALTER TABLE IF EXISTS ONLY public.wt_site_setting DROP CONSTRAINT IF EXISTS wt_site_setting_pkey;
ALTER TABLE IF EXISTS ONLY public.wt_session DROP CONSTRAINT IF EXISTS wt_session_pkey;
ALTER TABLE IF EXISTS ONLY public.wt_places DROP CONSTRAINT IF EXISTS wt_places_pkey;
ALTER TABLE IF EXISTS ONLY public.wt_places DROP CONSTRAINT IF EXISTS wt_places_p_parent_id_p_file_p_place_unique;
ALTER TABLE IF EXISTS ONLY public.wt_placelinks DROP CONSTRAINT IF EXISTS wt_placelinks_pkey;
ALTER TABLE IF EXISTS ONLY public.wt_place_location DROP CONSTRAINT IF EXISTS wt_place_location_place_parent_id_unique;
ALTER TABLE IF EXISTS ONLY public.wt_place_location DROP CONSTRAINT IF EXISTS wt_place_location_pkey;
ALTER TABLE IF EXISTS ONLY public.wt_place_location DROP CONSTRAINT IF EXISTS wt_place_location_parent_id_place_unique;
ALTER TABLE IF EXISTS ONLY public.wt_other DROP CONSTRAINT IF EXISTS wt_other_pkey;
ALTER TABLE IF EXISTS ONLY public.wt_other DROP CONSTRAINT IF EXISTS wt_other_o_file_o_id_unique;
ALTER TABLE IF EXISTS ONLY public.wt_news DROP CONSTRAINT IF EXISTS wt_news_pkey;
ALTER TABLE IF EXISTS ONLY public.wt_name DROP CONSTRAINT IF EXISTS wt_name_pkey;
ALTER TABLE IF EXISTS ONLY public.wt_module_setting DROP CONSTRAINT IF EXISTS wt_module_setting_pkey;
ALTER TABLE IF EXISTS ONLY public.wt_module_privacy DROP CONSTRAINT IF EXISTS wt_module_privacy_pkey;
ALTER TABLE IF EXISTS ONLY public.wt_module_privacy DROP CONSTRAINT IF EXISTS wt_module_privacy_ix2;
ALTER TABLE IF EXISTS ONLY public.wt_module_privacy DROP CONSTRAINT IF EXISTS wt_module_privacy_ix1;
ALTER TABLE IF EXISTS ONLY public.wt_module DROP CONSTRAINT IF EXISTS wt_module_pkey;
ALTER TABLE IF EXISTS ONLY public.wt_message DROP CONSTRAINT IF EXISTS wt_message_pkey;
ALTER TABLE IF EXISTS ONLY public.wt_media DROP CONSTRAINT IF EXISTS wt_media_pkey;
ALTER TABLE IF EXISTS ONLY public.wt_media DROP CONSTRAINT IF EXISTS wt_media_m_id_m_file_unique;
ALTER TABLE IF EXISTS ONLY public.wt_media_file DROP CONSTRAINT IF EXISTS wt_media_file_pkey;
ALTER TABLE IF EXISTS ONLY public.wt_log DROP CONSTRAINT IF EXISTS wt_log_pkey;
ALTER TABLE IF EXISTS ONLY public.wt_link DROP CONSTRAINT IF EXISTS wt_link_pkey;
ALTER TABLE IF EXISTS ONLY public.wt_link DROP CONSTRAINT IF EXISTS wt_link_l_to_l_file_l_type_l_from_unique;
ALTER TABLE IF EXISTS ONLY public.wt_individuals DROP CONSTRAINT IF EXISTS wt_individuals_pkey;
ALTER TABLE IF EXISTS ONLY public.wt_individuals DROP CONSTRAINT IF EXISTS wt_individuals_i_file_i_id_unique;
ALTER TABLE IF EXISTS ONLY public.wt_hit_counter DROP CONSTRAINT IF EXISTS wt_hit_counter_pkey;
ALTER TABLE IF EXISTS ONLY public.wt_gedcom_setting DROP CONSTRAINT IF EXISTS wt_gedcom_setting_pkey;
ALTER TABLE IF EXISTS ONLY public.wt_gedcom DROP CONSTRAINT IF EXISTS wt_gedcom_pkey;
ALTER TABLE IF EXISTS ONLY public.wt_gedcom DROP CONSTRAINT IF EXISTS wt_gedcom_gedcom_name_unique;
ALTER TABLE IF EXISTS ONLY public.wt_gedcom_chunk DROP CONSTRAINT IF EXISTS wt_gedcom_chunk_pkey;
ALTER TABLE IF EXISTS ONLY public.wt_favorite DROP CONSTRAINT IF EXISTS wt_favorite_pkey;
ALTER TABLE IF EXISTS ONLY public.wt_families DROP CONSTRAINT IF EXISTS wt_families_pkey;
ALTER TABLE IF EXISTS ONLY public.wt_families DROP CONSTRAINT IF EXISTS wt_families_f_file_f_id_unique;
ALTER TABLE IF EXISTS ONLY public.wt_default_resn DROP CONSTRAINT IF EXISTS wt_default_resn_pkey;
ALTER TABLE IF EXISTS ONLY public.wt_default_resn DROP CONSTRAINT IF EXISTS wt_default_resn_gedcom_id_xref_tag_type_unique;
ALTER TABLE IF EXISTS ONLY public.wt_change DROP CONSTRAINT IF EXISTS wt_change_pkey;
ALTER TABLE IF EXISTS ONLY public.wt_block_setting DROP CONSTRAINT IF EXISTS wt_block_setting_pkey;
ALTER TABLE IF EXISTS ONLY public.wt_block DROP CONSTRAINT IF EXISTS wt_block_pkey;
ALTER TABLE IF EXISTS public.wt_user ALTER COLUMN user_id DROP DEFAULT;
ALTER TABLE IF EXISTS public.wt_places ALTER COLUMN p_id DROP DEFAULT;
ALTER TABLE IF EXISTS public.wt_place_location ALTER COLUMN id DROP DEFAULT;
ALTER TABLE IF EXISTS public.wt_news ALTER COLUMN news_id DROP DEFAULT;
ALTER TABLE IF EXISTS public.wt_module_privacy ALTER COLUMN id DROP DEFAULT;
ALTER TABLE IF EXISTS public.wt_message ALTER COLUMN message_id DROP DEFAULT;
ALTER TABLE IF EXISTS public.wt_media_file ALTER COLUMN id DROP DEFAULT;
ALTER TABLE IF EXISTS public.wt_log ALTER COLUMN log_id DROP DEFAULT;
ALTER TABLE IF EXISTS public.wt_gedcom_chunk ALTER COLUMN gedcom_chunk_id DROP DEFAULT;
ALTER TABLE IF EXISTS public.wt_gedcom ALTER COLUMN gedcom_id DROP DEFAULT;
ALTER TABLE IF EXISTS public.wt_favorite ALTER COLUMN favorite_id DROP DEFAULT;
ALTER TABLE IF EXISTS public.wt_default_resn ALTER COLUMN default_resn_id DROP DEFAULT;
ALTER TABLE IF EXISTS public.wt_change ALTER COLUMN change_id DROP DEFAULT;
ALTER TABLE IF EXISTS public.wt_block ALTER COLUMN block_id DROP DEFAULT;
DROP SEQUENCE IF EXISTS public.wt_user_user_id_seq;
DROP TABLE IF EXISTS public.wt_user_setting;
DROP TABLE IF EXISTS public.wt_user_gedcom_setting;
DROP TABLE IF EXISTS public.wt_user;
DROP TABLE IF EXISTS public.wt_sources;
DROP TABLE IF EXISTS public.wt_site_setting;
DROP TABLE IF EXISTS public.wt_session;
DROP SEQUENCE IF EXISTS public.wt_places_p_id_seq;
DROP TABLE IF EXISTS public.wt_places;
DROP TABLE IF EXISTS public.wt_placelinks;
DROP SEQUENCE IF EXISTS public.wt_place_location_id_seq;
DROP TABLE IF EXISTS public.wt_place_location;
DROP TABLE IF EXISTS public.wt_other;
DROP SEQUENCE IF EXISTS public.wt_news_news_id_seq;
DROP TABLE IF EXISTS public.wt_news;
DROP TABLE IF EXISTS public.wt_name;
DROP TABLE IF EXISTS public.wt_module_setting;
DROP SEQUENCE IF EXISTS public.wt_module_privacy_id_seq;
DROP TABLE IF EXISTS public.wt_module_privacy;
DROP TABLE IF EXISTS public.wt_module;
DROP SEQUENCE IF EXISTS public.wt_message_message_id_seq;
DROP TABLE IF EXISTS public.wt_message;
DROP SEQUENCE IF EXISTS public.wt_media_file_id_seq;
DROP TABLE IF EXISTS public.wt_media_file;
DROP TABLE IF EXISTS public.wt_media;
DROP SEQUENCE IF EXISTS public.wt_log_log_id_seq;
DROP TABLE IF EXISTS public.wt_log;
DROP TABLE IF EXISTS public.wt_link;
DROP TABLE IF EXISTS public.wt_individuals;
DROP TABLE IF EXISTS public.wt_hit_counter;
DROP TABLE IF EXISTS public.wt_gedcom_setting;
DROP SEQUENCE IF EXISTS public.wt_gedcom_gedcom_id_seq;
DROP SEQUENCE IF EXISTS public.wt_gedcom_chunk_gedcom_chunk_id_seq;
DROP TABLE IF EXISTS public.wt_gedcom_chunk;
DROP TABLE IF EXISTS public.wt_gedcom;
DROP SEQUENCE IF EXISTS public.wt_favorite_favorite_id_seq;
DROP TABLE IF EXISTS public.wt_favorite;
DROP TABLE IF EXISTS public.wt_families;
DROP SEQUENCE IF EXISTS public.wt_default_resn_default_resn_id_seq;
DROP TABLE IF EXISTS public.wt_default_resn;
DROP TABLE IF EXISTS public.wt_dates;
DROP SEQUENCE IF EXISTS public.wt_change_change_id_seq;
DROP TABLE IF EXISTS public.wt_change;
DROP TABLE IF EXISTS public.wt_block_setting;
DROP SEQUENCE IF EXISTS public.wt_block_block_id_seq;
DROP TABLE IF EXISTS public.wt_block;
SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: wt_block; Type: TABLE; Schema: public; Owner: webtrees
--

CREATE TABLE public.wt_block (
    block_id integer NOT NULL,
    gedcom_id integer,
    user_id integer,
    xref character varying(20),
    location character varying(255),
    block_order integer NOT NULL,
    module_name character varying(32) NOT NULL,
    CONSTRAINT wt_block_location_check CHECK (((location)::text = ANY (ARRAY[('main'::character varying)::text, ('side'::character varying)::text])))
);


ALTER TABLE public.wt_block OWNER TO webtrees;

--
-- Name: wt_block_block_id_seq; Type: SEQUENCE; Schema: public; Owner: webtrees
--

CREATE SEQUENCE public.wt_block_block_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.wt_block_block_id_seq OWNER TO webtrees;

--
-- Name: wt_block_block_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: webtrees
--

ALTER SEQUENCE public.wt_block_block_id_seq OWNED BY public.wt_block.block_id;


--
-- Name: wt_block_setting; Type: TABLE; Schema: public; Owner: webtrees
--

CREATE TABLE public.wt_block_setting (
    block_id integer NOT NULL,
    setting_name character varying(32) NOT NULL,
    setting_value text NOT NULL
);


ALTER TABLE public.wt_block_setting OWNER TO webtrees;

--
-- Name: wt_change; Type: TABLE; Schema: public; Owner: webtrees
--

CREATE TABLE public.wt_change (
    change_id integer NOT NULL,
    change_time timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    status character varying(255) DEFAULT 'pending'::character varying NOT NULL,
    gedcom_id integer NOT NULL,
    xref character varying(20) NOT NULL,
    old_gedcom text NOT NULL,
    new_gedcom text NOT NULL,
    user_id integer NOT NULL,
    CONSTRAINT wt_change_status_check CHECK (((status)::text = ANY (ARRAY[('accepted'::character varying)::text, ('pending'::character varying)::text, ('rejected'::character varying)::text])))
);


ALTER TABLE public.wt_change OWNER TO webtrees;

--
-- Name: wt_change_change_id_seq; Type: SEQUENCE; Schema: public; Owner: webtrees
--

CREATE SEQUENCE public.wt_change_change_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.wt_change_change_id_seq OWNER TO webtrees;

--
-- Name: wt_change_change_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: webtrees
--

ALTER SEQUENCE public.wt_change_change_id_seq OWNED BY public.wt_change.change_id;


--
-- Name: wt_dates; Type: TABLE; Schema: public; Owner: webtrees
--

CREATE TABLE public.wt_dates (
    d_day smallint NOT NULL,
    d_month character(5),
    d_mon smallint NOT NULL,
    d_year smallint NOT NULL,
    d_julianday1 integer NOT NULL,
    d_julianday2 integer NOT NULL,
    d_fact character varying(15) NOT NULL,
    d_gid character varying(20) NOT NULL,
    d_file integer NOT NULL,
    d_type character varying(255) NOT NULL,
    CONSTRAINT wt_dates_d_type_check CHECK (((d_type)::text = ANY (ARRAY[('@#DGREGORIAN@'::character varying)::text, ('@#DJULIAN@'::character varying)::text, ('@#DHEBREW@'::character varying)::text, ('@#DFRENCH R@'::character varying)::text, ('@#DHIJRI@'::character varying)::text, ('@#DROMAN@'::character varying)::text, ('@#DJALALI@'::character varying)::text])))
);


ALTER TABLE public.wt_dates OWNER TO webtrees;

--
-- Name: wt_default_resn; Type: TABLE; Schema: public; Owner: webtrees
--

CREATE TABLE public.wt_default_resn (
    default_resn_id integer NOT NULL,
    gedcom_id integer NOT NULL,
    xref character varying(20),
    tag_type character varying(15),
    resn character varying(255) NOT NULL,
    comment character varying(255),
    updated timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT wt_default_resn_resn_check CHECK (((resn)::text = ANY (ARRAY[('none'::character varying)::text, ('privacy'::character varying)::text, ('confidential'::character varying)::text, ('hidden'::character varying)::text])))
);


ALTER TABLE public.wt_default_resn OWNER TO webtrees;

--
-- Name: wt_default_resn_default_resn_id_seq; Type: SEQUENCE; Schema: public; Owner: webtrees
--

CREATE SEQUENCE public.wt_default_resn_default_resn_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.wt_default_resn_default_resn_id_seq OWNER TO webtrees;

--
-- Name: wt_default_resn_default_resn_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: webtrees
--

ALTER SEQUENCE public.wt_default_resn_default_resn_id_seq OWNED BY public.wt_default_resn.default_resn_id;


--
-- Name: wt_families; Type: TABLE; Schema: public; Owner: webtrees
--

CREATE TABLE public.wt_families (
    f_id character varying(20) NOT NULL,
    f_file integer NOT NULL,
    f_husb character varying(20),
    f_wife character varying(20),
    f_gedcom text NOT NULL,
    f_numchil integer NOT NULL
);


ALTER TABLE public.wt_families OWNER TO webtrees;

--
-- Name: wt_favorite; Type: TABLE; Schema: public; Owner: webtrees
--

CREATE TABLE public.wt_favorite (
    favorite_id integer NOT NULL,
    user_id integer,
    gedcom_id integer NOT NULL,
    xref character varying(20),
    favorite_type character varying(255) NOT NULL,
    url character varying(255),
    title character varying(255),
    note character varying(1000),
    CONSTRAINT wt_favorite_favorite_type_check CHECK (((favorite_type)::text = ANY (ARRAY[('INDI'::character varying)::text, ('FAM'::character varying)::text, ('SOUR'::character varying)::text, ('REPO'::character varying)::text, ('OBJE'::character varying)::text, ('NOTE'::character varying)::text, ('URL'::character varying)::text])))
);


ALTER TABLE public.wt_favorite OWNER TO webtrees;

--
-- Name: wt_favorite_favorite_id_seq; Type: SEQUENCE; Schema: public; Owner: webtrees
--

CREATE SEQUENCE public.wt_favorite_favorite_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.wt_favorite_favorite_id_seq OWNER TO webtrees;

--
-- Name: wt_favorite_favorite_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: webtrees
--

ALTER SEQUENCE public.wt_favorite_favorite_id_seq OWNED BY public.wt_favorite.favorite_id;


--
-- Name: wt_gedcom; Type: TABLE; Schema: public; Owner: webtrees
--

CREATE TABLE public.wt_gedcom (
    gedcom_id integer NOT NULL,
    gedcom_name character varying(255) NOT NULL,
    sort_order integer DEFAULT 0 NOT NULL
);


ALTER TABLE public.wt_gedcom OWNER TO webtrees;

--
-- Name: wt_gedcom_chunk; Type: TABLE; Schema: public; Owner: webtrees
--

CREATE TABLE public.wt_gedcom_chunk (
    gedcom_chunk_id integer NOT NULL,
    gedcom_id integer NOT NULL,
    chunk_data text NOT NULL,
    imported boolean DEFAULT false NOT NULL
);


ALTER TABLE public.wt_gedcom_chunk OWNER TO webtrees;

--
-- Name: wt_gedcom_chunk_gedcom_chunk_id_seq; Type: SEQUENCE; Schema: public; Owner: webtrees
--

CREATE SEQUENCE public.wt_gedcom_chunk_gedcom_chunk_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.wt_gedcom_chunk_gedcom_chunk_id_seq OWNER TO webtrees;

--
-- Name: wt_gedcom_chunk_gedcom_chunk_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: webtrees
--

ALTER SEQUENCE public.wt_gedcom_chunk_gedcom_chunk_id_seq OWNED BY public.wt_gedcom_chunk.gedcom_chunk_id;


--
-- Name: wt_gedcom_gedcom_id_seq; Type: SEQUENCE; Schema: public; Owner: webtrees
--

CREATE SEQUENCE public.wt_gedcom_gedcom_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.wt_gedcom_gedcom_id_seq OWNER TO webtrees;

--
-- Name: wt_gedcom_gedcom_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: webtrees
--

ALTER SEQUENCE public.wt_gedcom_gedcom_id_seq OWNED BY public.wt_gedcom.gedcom_id;


--
-- Name: wt_gedcom_setting; Type: TABLE; Schema: public; Owner: webtrees
--

CREATE TABLE public.wt_gedcom_setting (
    gedcom_id integer NOT NULL,
    setting_name character varying(32) NOT NULL,
    setting_value character varying(255) NOT NULL
);


ALTER TABLE public.wt_gedcom_setting OWNER TO webtrees;

--
-- Name: wt_hit_counter; Type: TABLE; Schema: public; Owner: webtrees
--

CREATE TABLE public.wt_hit_counter (
    gedcom_id integer NOT NULL,
    page_name character varying(32) NOT NULL,
    page_parameter character varying(32) NOT NULL,
    page_count integer NOT NULL
);


ALTER TABLE public.wt_hit_counter OWNER TO webtrees;

--
-- Name: wt_individuals; Type: TABLE; Schema: public; Owner: webtrees
--

CREATE TABLE public.wt_individuals (
    i_id character varying(20) NOT NULL,
    i_file integer NOT NULL,
    i_rin character varying(20) NOT NULL,
    i_sex character varying(255) NOT NULL,
    i_gedcom text NOT NULL,
    CONSTRAINT wt_individuals_i_sex_check CHECK (((i_sex)::text = ANY (ARRAY[('U'::character varying)::text, ('M'::character varying)::text, ('F'::character varying)::text])))
);


ALTER TABLE public.wt_individuals OWNER TO webtrees;

--
-- Name: wt_link; Type: TABLE; Schema: public; Owner: webtrees
--

CREATE TABLE public.wt_link (
    l_file integer NOT NULL,
    l_from character varying(20) NOT NULL,
    l_type character varying(15) NOT NULL,
    l_to character varying(20) NOT NULL
);


ALTER TABLE public.wt_link OWNER TO webtrees;

--
-- Name: wt_log; Type: TABLE; Schema: public; Owner: webtrees
--

CREATE TABLE public.wt_log (
    log_id integer NOT NULL,
    log_time timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    log_type character varying(255) NOT NULL,
    log_message text NOT NULL,
    ip_address inet NOT NULL,
    user_id integer,
    gedcom_id integer,
    CONSTRAINT wt_log_log_type_check CHECK (((log_type)::text = ANY (ARRAY[('auth'::character varying)::text, ('config'::character varying)::text, ('debug'::character varying)::text, ('edit'::character varying)::text, ('error'::character varying)::text, ('media'::character varying)::text, ('search'::character varying)::text])))
);


ALTER TABLE public.wt_log OWNER TO webtrees;

--
-- Name: wt_log_log_id_seq; Type: SEQUENCE; Schema: public; Owner: webtrees
--

CREATE SEQUENCE public.wt_log_log_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.wt_log_log_id_seq OWNER TO webtrees;

--
-- Name: wt_log_log_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: webtrees
--

ALTER SEQUENCE public.wt_log_log_id_seq OWNED BY public.wt_log.log_id;


--
-- Name: wt_media; Type: TABLE; Schema: public; Owner: webtrees
--

CREATE TABLE public.wt_media (
    m_id character varying(20) NOT NULL,
    m_file integer NOT NULL,
    m_gedcom text
);


ALTER TABLE public.wt_media OWNER TO webtrees;

--
-- Name: wt_media_file; Type: TABLE; Schema: public; Owner: webtrees
--

CREATE TABLE public.wt_media_file (
    id integer NOT NULL,
    m_id character varying(20) NOT NULL,
    m_file integer NOT NULL,
    multimedia_file_refn character varying(248) NOT NULL,
    multimedia_format character varying(4) NOT NULL,
    source_media_type character varying(15) NOT NULL,
    descriptive_title character varying(248) NOT NULL
);


ALTER TABLE public.wt_media_file OWNER TO webtrees;

--
-- Name: wt_media_file_id_seq; Type: SEQUENCE; Schema: public; Owner: webtrees
--

CREATE SEQUENCE public.wt_media_file_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.wt_media_file_id_seq OWNER TO webtrees;

--
-- Name: wt_media_file_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: webtrees
--

ALTER SEQUENCE public.wt_media_file_id_seq OWNED BY public.wt_media_file.id;


--
-- Name: wt_message; Type: TABLE; Schema: public; Owner: webtrees
--

CREATE TABLE public.wt_message (
    message_id integer NOT NULL,
    sender character varying(64) NOT NULL,
    ip_address inet NOT NULL,
    user_id integer NOT NULL,
    subject character varying(255) NOT NULL,
    body text NOT NULL,
    created timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE public.wt_message OWNER TO webtrees;

--
-- Name: wt_message_message_id_seq; Type: SEQUENCE; Schema: public; Owner: webtrees
--

CREATE SEQUENCE public.wt_message_message_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.wt_message_message_id_seq OWNER TO webtrees;

--
-- Name: wt_message_message_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: webtrees
--

ALTER SEQUENCE public.wt_message_message_id_seq OWNED BY public.wt_message.message_id;


--
-- Name: wt_module; Type: TABLE; Schema: public; Owner: webtrees
--

CREATE TABLE public.wt_module (
    module_name character varying(32) NOT NULL,
    status character varying(255) DEFAULT 'enabled'::character varying NOT NULL,
    tab_order integer,
    menu_order integer,
    sidebar_order integer,
    footer_order integer,
    CONSTRAINT wt_module_status_check CHECK (((status)::text = ANY (ARRAY[('enabled'::character varying)::text, ('disabled'::character varying)::text])))
);


ALTER TABLE public.wt_module OWNER TO webtrees;

--
-- Name: wt_module_privacy; Type: TABLE; Schema: public; Owner: webtrees
--

CREATE TABLE public.wt_module_privacy (
    id integer NOT NULL,
    module_name character varying(32) NOT NULL,
    gedcom_id integer NOT NULL,
    interface character varying(255) NOT NULL,
    access_level smallint NOT NULL
);


ALTER TABLE public.wt_module_privacy OWNER TO webtrees;

--
-- Name: wt_module_privacy_id_seq; Type: SEQUENCE; Schema: public; Owner: webtrees
--

CREATE SEQUENCE public.wt_module_privacy_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.wt_module_privacy_id_seq OWNER TO webtrees;

--
-- Name: wt_module_privacy_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: webtrees
--

ALTER SEQUENCE public.wt_module_privacy_id_seq OWNED BY public.wt_module_privacy.id;


--
-- Name: wt_module_setting; Type: TABLE; Schema: public; Owner: webtrees
--

CREATE TABLE public.wt_module_setting (
    module_name character varying(32) NOT NULL,
    setting_name character varying(32) NOT NULL,
    setting_value text NOT NULL
);


ALTER TABLE public.wt_module_setting OWNER TO webtrees;

--
-- Name: wt_name; Type: TABLE; Schema: public; Owner: webtrees
--

CREATE TABLE public.wt_name (
    n_file integer NOT NULL,
    n_id character varying(20) NOT NULL,
    n_num integer NOT NULL,
    n_type character varying(15) NOT NULL,
    n_sort character varying(255) NOT NULL,
    n_full character varying(255) NOT NULL,
    n_surname character varying(255),
    n_surn character varying(255),
    n_givn character varying(255),
    n_soundex_givn_std character varying(255),
    n_soundex_surn_std character varying(255),
    n_soundex_givn_dm character varying(255),
    n_soundex_surn_dm character varying(255)
);


ALTER TABLE public.wt_name OWNER TO webtrees;

--
-- Name: wt_news; Type: TABLE; Schema: public; Owner: webtrees
--

CREATE TABLE public.wt_news (
    news_id integer NOT NULL,
    user_id integer,
    gedcom_id integer,
    subject character varying(255) NOT NULL,
    body text NOT NULL,
    updated timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE public.wt_news OWNER TO webtrees;

--
-- Name: wt_news_news_id_seq; Type: SEQUENCE; Schema: public; Owner: webtrees
--

CREATE SEQUENCE public.wt_news_news_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.wt_news_news_id_seq OWNER TO webtrees;

--
-- Name: wt_news_news_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: webtrees
--

ALTER SEQUENCE public.wt_news_news_id_seq OWNED BY public.wt_news.news_id;


--
-- Name: wt_other; Type: TABLE; Schema: public; Owner: webtrees
--

CREATE TABLE public.wt_other (
    o_id character varying(20) NOT NULL,
    o_file integer NOT NULL,
    o_type character varying(15) NOT NULL,
    o_gedcom text NOT NULL
);


ALTER TABLE public.wt_other OWNER TO webtrees;

--
-- Name: wt_place_location; Type: TABLE; Schema: public; Owner: webtrees
--

CREATE TABLE public.wt_place_location (
    id integer NOT NULL,
    parent_id integer,
    place character varying(120) NOT NULL,
    latitude double precision,
    longitude double precision
);


ALTER TABLE public.wt_place_location OWNER TO webtrees;

--
-- Name: wt_place_location_id_seq; Type: SEQUENCE; Schema: public; Owner: webtrees
--

CREATE SEQUENCE public.wt_place_location_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.wt_place_location_id_seq OWNER TO webtrees;

--
-- Name: wt_place_location_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: webtrees
--

ALTER SEQUENCE public.wt_place_location_id_seq OWNED BY public.wt_place_location.id;


--
-- Name: wt_placelinks; Type: TABLE; Schema: public; Owner: webtrees
--

CREATE TABLE public.wt_placelinks (
    pl_p_id integer NOT NULL,
    pl_gid character varying(20) NOT NULL,
    pl_file integer NOT NULL
);


ALTER TABLE public.wt_placelinks OWNER TO webtrees;

--
-- Name: wt_places; Type: TABLE; Schema: public; Owner: webtrees
--

CREATE TABLE public.wt_places (
    p_id integer NOT NULL,
    p_place character varying(150) NOT NULL,
    p_parent_id integer,
    p_file integer NOT NULL,
    p_std_soundex text,
    p_dm_soundex text
);


ALTER TABLE public.wt_places OWNER TO webtrees;

--
-- Name: wt_places_p_id_seq; Type: SEQUENCE; Schema: public; Owner: webtrees
--

CREATE SEQUENCE public.wt_places_p_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.wt_places_p_id_seq OWNER TO webtrees;

--
-- Name: wt_places_p_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: webtrees
--

ALTER SEQUENCE public.wt_places_p_id_seq OWNED BY public.wt_places.p_id;


--
-- Name: wt_session; Type: TABLE; Schema: public; Owner: webtrees
--

CREATE TABLE public.wt_session (
    session_id character varying(256) NOT NULL,
    session_time timestamp(0) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    user_id integer NOT NULL,
    ip_address inet NOT NULL,
    session_data text NOT NULL
);


ALTER TABLE public.wt_session OWNER TO webtrees;

--
-- Name: wt_site_setting; Type: TABLE; Schema: public; Owner: webtrees
--

CREATE TABLE public.wt_site_setting (
    setting_name character varying(32) NOT NULL,
    setting_value character varying(2000) NOT NULL
);


ALTER TABLE public.wt_site_setting OWNER TO webtrees;

--
-- Name: wt_sources; Type: TABLE; Schema: public; Owner: webtrees
--

CREATE TABLE public.wt_sources (
    s_id character varying(20) NOT NULL,
    s_file integer NOT NULL,
    s_name character varying(255) NOT NULL,
    s_gedcom text NOT NULL
);


ALTER TABLE public.wt_sources OWNER TO webtrees;

--
-- Name: wt_user; Type: TABLE; Schema: public; Owner: webtrees
--

CREATE TABLE public.wt_user (
    user_id integer NOT NULL,
    user_name character varying(32) NOT NULL,
    real_name character varying(64) NOT NULL,
    email character varying(64) NOT NULL,
    password character varying(128) NOT NULL
);


ALTER TABLE public.wt_user OWNER TO webtrees;

--
-- Name: wt_user_gedcom_setting; Type: TABLE; Schema: public; Owner: webtrees
--

CREATE TABLE public.wt_user_gedcom_setting (
    user_id integer NOT NULL,
    gedcom_id integer NOT NULL,
    setting_name character varying(32) NOT NULL,
    setting_value character varying(255) NOT NULL
);


ALTER TABLE public.wt_user_gedcom_setting OWNER TO webtrees;

--
-- Name: wt_user_setting; Type: TABLE; Schema: public; Owner: webtrees
--

CREATE TABLE public.wt_user_setting (
    user_id integer NOT NULL,
    setting_name character varying(32) NOT NULL,
    setting_value character varying(255) NOT NULL
);


ALTER TABLE public.wt_user_setting OWNER TO webtrees;

--
-- Name: wt_user_user_id_seq; Type: SEQUENCE; Schema: public; Owner: webtrees
--

CREATE SEQUENCE public.wt_user_user_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.wt_user_user_id_seq OWNER TO webtrees;

--
-- Name: wt_user_user_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: webtrees
--

ALTER SEQUENCE public.wt_user_user_id_seq OWNED BY public.wt_user.user_id;


--
-- Name: wt_block block_id; Type: DEFAULT; Schema: public; Owner: webtrees
--

ALTER TABLE ONLY public.wt_block ALTER COLUMN block_id SET DEFAULT nextval('public.wt_block_block_id_seq'::regclass);


--
-- Name: wt_change change_id; Type: DEFAULT; Schema: public; Owner: webtrees
--

ALTER TABLE ONLY public.wt_change ALTER COLUMN change_id SET DEFAULT nextval('public.wt_change_change_id_seq'::regclass);


--
-- Name: wt_default_resn default_resn_id; Type: DEFAULT; Schema: public; Owner: webtrees
--

ALTER TABLE ONLY public.wt_default_resn ALTER COLUMN default_resn_id SET DEFAULT nextval('public.wt_default_resn_default_resn_id_seq'::regclass);


--
-- Name: wt_favorite favorite_id; Type: DEFAULT; Schema: public; Owner: webtrees
--

ALTER TABLE ONLY public.wt_favorite ALTER COLUMN favorite_id SET DEFAULT nextval('public.wt_favorite_favorite_id_seq'::regclass);


--
-- Name: wt_gedcom gedcom_id; Type: DEFAULT; Schema: public; Owner: webtrees
--

ALTER TABLE ONLY public.wt_gedcom ALTER COLUMN gedcom_id SET DEFAULT nextval('public.wt_gedcom_gedcom_id_seq'::regclass);


--
-- Name: wt_gedcom_chunk gedcom_chunk_id; Type: DEFAULT; Schema: public; Owner: webtrees
--

ALTER TABLE ONLY public.wt_gedcom_chunk ALTER COLUMN gedcom_chunk_id SET DEFAULT nextval('public.wt_gedcom_chunk_gedcom_chunk_id_seq'::regclass);


--
-- Name: wt_log log_id; Type: DEFAULT; Schema: public; Owner: webtrees
--

ALTER TABLE ONLY public.wt_log ALTER COLUMN log_id SET DEFAULT nextval('public.wt_log_log_id_seq'::regclass);


--
-- Name: wt_media_file id; Type: DEFAULT; Schema: public; Owner: webtrees
--

ALTER TABLE ONLY public.wt_media_file ALTER COLUMN id SET DEFAULT nextval('public.wt_media_file_id_seq'::regclass);


--
-- Name: wt_message message_id; Type: DEFAULT; Schema: public; Owner: webtrees
--

ALTER TABLE ONLY public.wt_message ALTER COLUMN message_id SET DEFAULT nextval('public.wt_message_message_id_seq'::regclass);


--
-- Name: wt_module_privacy id; Type: DEFAULT; Schema: public; Owner: webtrees
--

ALTER TABLE ONLY public.wt_module_privacy ALTER COLUMN id SET DEFAULT nextval('public.wt_module_privacy_id_seq'::regclass);


--
-- Name: wt_news news_id; Type: DEFAULT; Schema: public; Owner: webtrees
--

ALTER TABLE ONLY public.wt_news ALTER COLUMN news_id SET DEFAULT nextval('public.wt_news_news_id_seq'::regclass);


--
-- Name: wt_place_location id; Type: DEFAULT; Schema: public; Owner: webtrees
--

ALTER TABLE ONLY public.wt_place_location ALTER COLUMN id SET DEFAULT nextval('public.wt_place_location_id_seq'::regclass);


--
-- Name: wt_places p_id; Type: DEFAULT; Schema: public; Owner: webtrees
--

ALTER TABLE ONLY public.wt_places ALTER COLUMN p_id SET DEFAULT nextval('public.wt_places_p_id_seq'::regclass);


--
-- Name: wt_user user_id; Type: DEFAULT; Schema: public; Owner: webtrees
--

ALTER TABLE ONLY public.wt_user ALTER COLUMN user_id SET DEFAULT nextval('public.wt_user_user_id_seq'::regclass);


--
-- Data for Name: wt_block; Type: TABLE DATA; Schema: public; Owner: webtrees
--



--
-- Data for Name: wt_block_setting; Type: TABLE DATA; Schema: public; Owner: webtrees
--



--
-- Data for Name: wt_change; Type: TABLE DATA; Schema: public; Owner: webtrees
--



--
-- Data for Name: wt_dates; Type: TABLE DATA; Schema: public; Owner: webtrees
--



--
-- Data for Name: wt_default_resn; Type: TABLE DATA; Schema: public; Owner: webtrees
--

INSERT INTO public.wt_default_resn VALUES (1, -1, NULL, 'SSN', 'confidential', NULL, '2025-12-07 14:02:09');
INSERT INTO public.wt_default_resn VALUES (2, -1, NULL, 'SOUR', 'privacy', NULL, '2025-12-07 14:02:09');
INSERT INTO public.wt_default_resn VALUES (3, -1, NULL, 'REPO', 'privacy', NULL, '2025-12-07 14:02:09');
INSERT INTO public.wt_default_resn VALUES (4, -1, NULL, 'SUBM', 'confidential', NULL, '2025-12-07 14:02:09');
INSERT INTO public.wt_default_resn VALUES (5, -1, NULL, 'SUBN', 'confidential', NULL, '2025-12-07 14:02:09');


--
-- Data for Name: wt_families; Type: TABLE DATA; Schema: public; Owner: webtrees
--



--
-- Data for Name: wt_favorite; Type: TABLE DATA; Schema: public; Owner: webtrees
--



--
-- Data for Name: wt_gedcom; Type: TABLE DATA; Schema: public; Owner: webtrees
--

INSERT INTO public.wt_gedcom VALUES (-1, 'DEFAULT_TREE', 0);


--
-- Data for Name: wt_gedcom_chunk; Type: TABLE DATA; Schema: public; Owner: webtrees
--



--
-- Data for Name: wt_gedcom_setting; Type: TABLE DATA; Schema: public; Owner: webtrees
--



--
-- Data for Name: wt_hit_counter; Type: TABLE DATA; Schema: public; Owner: webtrees
--



--
-- Data for Name: wt_individuals; Type: TABLE DATA; Schema: public; Owner: webtrees
--



--
-- Data for Name: wt_link; Type: TABLE DATA; Schema: public; Owner: webtrees
--



--
-- Data for Name: wt_log; Type: TABLE DATA; Schema: public; Owner: webtrees
--



--
-- Data for Name: wt_media; Type: TABLE DATA; Schema: public; Owner: webtrees
--



--
-- Data for Name: wt_media_file; Type: TABLE DATA; Schema: public; Owner: webtrees
--



--
-- Data for Name: wt_message; Type: TABLE DATA; Schema: public; Owner: webtrees
--



--
-- Data for Name: wt_module; Type: TABLE DATA; Schema: public; Owner: webtrees
--



--
-- Data for Name: wt_module_privacy; Type: TABLE DATA; Schema: public; Owner: webtrees
--



--
-- Data for Name: wt_module_setting; Type: TABLE DATA; Schema: public; Owner: webtrees
--



--
-- Data for Name: wt_name; Type: TABLE DATA; Schema: public; Owner: webtrees
--



--
-- Data for Name: wt_news; Type: TABLE DATA; Schema: public; Owner: webtrees
--



--
-- Data for Name: wt_other; Type: TABLE DATA; Schema: public; Owner: webtrees
--



--
-- Data for Name: wt_place_location; Type: TABLE DATA; Schema: public; Owner: webtrees
--



--
-- Data for Name: wt_placelinks; Type: TABLE DATA; Schema: public; Owner: webtrees
--



--
-- Data for Name: wt_places; Type: TABLE DATA; Schema: public; Owner: webtrees
--



--
-- Data for Name: wt_session; Type: TABLE DATA; Schema: public; Owner: webtrees
--



--
-- Data for Name: wt_site_setting; Type: TABLE DATA; Schema: public; Owner: webtrees
--

INSERT INTO public.wt_site_setting VALUES ('ALLOW_CHANGE_GEDCOM', '1');
INSERT INTO public.wt_site_setting VALUES ('INDEX_DIRECTORY', 'data/');
INSERT INTO public.wt_site_setting VALUES ('SMTP_ACTIVE', 'internal');
INSERT INTO public.wt_site_setting VALUES ('SMTP_AUTH', '1');
INSERT INTO public.wt_site_setting VALUES ('SMTP_HOST', 'localhost');
INSERT INTO public.wt_site_setting VALUES ('SMTP_PORT', '25');
INSERT INTO public.wt_site_setting VALUES ('SMTP_SSL', 'none');
INSERT INTO public.wt_site_setting VALUES ('USE_REGISTRATION_MODULE', '1');
INSERT INTO public.wt_site_setting VALUES ('WT_SCHEMA_VERSION', '45');


--
-- Data for Name: wt_sources; Type: TABLE DATA; Schema: public; Owner: webtrees
--



--
-- Data for Name: wt_user; Type: TABLE DATA; Schema: public; Owner: webtrees
--

INSERT INTO public.wt_user VALUES (-1, 'DEFAULT_USER', 'DEFAULT_USER', 'DEFAULT_USER', 'DEFAULT_USER');
INSERT INTO public.wt_user VALUES (1, '<WT_ADMIN_NAME>', 'Admin', '<WT_ADMIN_MAIL>', '<WT_ADMIN_PW>');


--
-- Data for Name: wt_user_gedcom_setting; Type: TABLE DATA; Schema: public; Owner: webtrees
--



--
-- Data for Name: wt_user_setting; Type: TABLE DATA; Schema: public; Owner: webtrees
--

INSERT INTO public.wt_user_setting VALUES (1, 'canadmin', '1');
INSERT INTO public.wt_user_setting VALUES (1, 'language', 'en-US');
INSERT INTO public.wt_user_setting VALUES (1, 'verified', '1');
INSERT INTO public.wt_user_setting VALUES (1, 'verified_by_admin', '1');
INSERT INTO public.wt_user_setting VALUES (1, 'visibleonline', '1');


--
-- Name: wt_block_block_id_seq; Type: SEQUENCE SET; Schema: public; Owner: webtrees
--

SELECT pg_catalog.setval('public.wt_block_block_id_seq', 1, false);


--
-- Name: wt_change_change_id_seq; Type: SEQUENCE SET; Schema: public; Owner: webtrees
--

SELECT pg_catalog.setval('public.wt_change_change_id_seq', 1, false);


--
-- Name: wt_default_resn_default_resn_id_seq; Type: SEQUENCE SET; Schema: public; Owner: webtrees
--

SELECT pg_catalog.setval('public.wt_default_resn_default_resn_id_seq', 5, true);


--
-- Name: wt_favorite_favorite_id_seq; Type: SEQUENCE SET; Schema: public; Owner: webtrees
--

SELECT pg_catalog.setval('public.wt_favorite_favorite_id_seq', 1, false);


--
-- Name: wt_gedcom_chunk_gedcom_chunk_id_seq; Type: SEQUENCE SET; Schema: public; Owner: webtrees
--

SELECT pg_catalog.setval('public.wt_gedcom_chunk_gedcom_chunk_id_seq', 1, false);


--
-- Name: wt_gedcom_gedcom_id_seq; Type: SEQUENCE SET; Schema: public; Owner: webtrees
--

SELECT pg_catalog.setval('public.wt_gedcom_gedcom_id_seq', 1, true);


--
-- Name: wt_log_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: webtrees
--

SELECT pg_catalog.setval('public.wt_log_log_id_seq', 1, false);


--
-- Name: wt_media_file_id_seq; Type: SEQUENCE SET; Schema: public; Owner: webtrees
--

SELECT pg_catalog.setval('public.wt_media_file_id_seq', 1, false);


--
-- Name: wt_message_message_id_seq; Type: SEQUENCE SET; Schema: public; Owner: webtrees
--

SELECT pg_catalog.setval('public.wt_message_message_id_seq', 1, false);


--
-- Name: wt_module_privacy_id_seq; Type: SEQUENCE SET; Schema: public; Owner: webtrees
--

SELECT pg_catalog.setval('public.wt_module_privacy_id_seq', 1, false);


--
-- Name: wt_news_news_id_seq; Type: SEQUENCE SET; Schema: public; Owner: webtrees
--

SELECT pg_catalog.setval('public.wt_news_news_id_seq', 1, false);


--
-- Name: wt_place_location_id_seq; Type: SEQUENCE SET; Schema: public; Owner: webtrees
--

SELECT pg_catalog.setval('public.wt_place_location_id_seq', 1, false);


--
-- Name: wt_places_p_id_seq; Type: SEQUENCE SET; Schema: public; Owner: webtrees
--

SELECT pg_catalog.setval('public.wt_places_p_id_seq', 1, false);


--
-- Name: wt_user_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: webtrees
--

SELECT pg_catalog.setval('public.wt_user_user_id_seq', 1, true);


--
-- Name: wt_block wt_block_pkey; Type: CONSTRAINT; Schema: public; Owner: webtrees
--

ALTER TABLE ONLY public.wt_block
    ADD CONSTRAINT wt_block_pkey PRIMARY KEY (block_id);


--
-- Name: wt_block_setting wt_block_setting_pkey; Type: CONSTRAINT; Schema: public; Owner: webtrees
--

ALTER TABLE ONLY public.wt_block_setting
    ADD CONSTRAINT wt_block_setting_pkey PRIMARY KEY (block_id, setting_name);


--
-- Name: wt_change wt_change_pkey; Type: CONSTRAINT; Schema: public; Owner: webtrees
--

ALTER TABLE ONLY public.wt_change
    ADD CONSTRAINT wt_change_pkey PRIMARY KEY (change_id);


--
-- Name: wt_default_resn wt_default_resn_gedcom_id_xref_tag_type_unique; Type: CONSTRAINT; Schema: public; Owner: webtrees
--

ALTER TABLE ONLY public.wt_default_resn
    ADD CONSTRAINT wt_default_resn_gedcom_id_xref_tag_type_unique UNIQUE (gedcom_id, xref, tag_type);


--
-- Name: wt_default_resn wt_default_resn_pkey; Type: CONSTRAINT; Schema: public; Owner: webtrees
--

ALTER TABLE ONLY public.wt_default_resn
    ADD CONSTRAINT wt_default_resn_pkey PRIMARY KEY (default_resn_id);


--
-- Name: wt_families wt_families_f_file_f_id_unique; Type: CONSTRAINT; Schema: public; Owner: webtrees
--

ALTER TABLE ONLY public.wt_families
    ADD CONSTRAINT wt_families_f_file_f_id_unique UNIQUE (f_file, f_id);


--
-- Name: wt_families wt_families_pkey; Type: CONSTRAINT; Schema: public; Owner: webtrees
--

ALTER TABLE ONLY public.wt_families
    ADD CONSTRAINT wt_families_pkey PRIMARY KEY (f_id, f_file);


--
-- Name: wt_favorite wt_favorite_pkey; Type: CONSTRAINT; Schema: public; Owner: webtrees
--

ALTER TABLE ONLY public.wt_favorite
    ADD CONSTRAINT wt_favorite_pkey PRIMARY KEY (favorite_id);


--
-- Name: wt_gedcom_chunk wt_gedcom_chunk_pkey; Type: CONSTRAINT; Schema: public; Owner: webtrees
--

ALTER TABLE ONLY public.wt_gedcom_chunk
    ADD CONSTRAINT wt_gedcom_chunk_pkey PRIMARY KEY (gedcom_chunk_id);


--
-- Name: wt_gedcom wt_gedcom_gedcom_name_unique; Type: CONSTRAINT; Schema: public; Owner: webtrees
--

ALTER TABLE ONLY public.wt_gedcom
    ADD CONSTRAINT wt_gedcom_gedcom_name_unique UNIQUE (gedcom_name);


--
-- Name: wt_gedcom wt_gedcom_pkey; Type: CONSTRAINT; Schema: public; Owner: webtrees
--

ALTER TABLE ONLY public.wt_gedcom
    ADD CONSTRAINT wt_gedcom_pkey PRIMARY KEY (gedcom_id);


--
-- Name: wt_gedcom_setting wt_gedcom_setting_pkey; Type: CONSTRAINT; Schema: public; Owner: webtrees
--

ALTER TABLE ONLY public.wt_gedcom_setting
    ADD CONSTRAINT wt_gedcom_setting_pkey PRIMARY KEY (gedcom_id, setting_name);


--
-- Name: wt_hit_counter wt_hit_counter_pkey; Type: CONSTRAINT; Schema: public; Owner: webtrees
--

ALTER TABLE ONLY public.wt_hit_counter
    ADD CONSTRAINT wt_hit_counter_pkey PRIMARY KEY (gedcom_id, page_name, page_parameter);


--
-- Name: wt_individuals wt_individuals_i_file_i_id_unique; Type: CONSTRAINT; Schema: public; Owner: webtrees
--

ALTER TABLE ONLY public.wt_individuals
    ADD CONSTRAINT wt_individuals_i_file_i_id_unique UNIQUE (i_file, i_id);


--
-- Name: wt_individuals wt_individuals_pkey; Type: CONSTRAINT; Schema: public; Owner: webtrees
--

ALTER TABLE ONLY public.wt_individuals
    ADD CONSTRAINT wt_individuals_pkey PRIMARY KEY (i_id, i_file);


--
-- Name: wt_link wt_link_l_to_l_file_l_type_l_from_unique; Type: CONSTRAINT; Schema: public; Owner: webtrees
--

ALTER TABLE ONLY public.wt_link
    ADD CONSTRAINT wt_link_l_to_l_file_l_type_l_from_unique UNIQUE (l_to, l_file, l_type, l_from);


--
-- Name: wt_link wt_link_pkey; Type: CONSTRAINT; Schema: public; Owner: webtrees
--

ALTER TABLE ONLY public.wt_link
    ADD CONSTRAINT wt_link_pkey PRIMARY KEY (l_from, l_file, l_type, l_to);


--
-- Name: wt_log wt_log_pkey; Type: CONSTRAINT; Schema: public; Owner: webtrees
--

ALTER TABLE ONLY public.wt_log
    ADD CONSTRAINT wt_log_pkey PRIMARY KEY (log_id);


--
-- Name: wt_media_file wt_media_file_pkey; Type: CONSTRAINT; Schema: public; Owner: webtrees
--

ALTER TABLE ONLY public.wt_media_file
    ADD CONSTRAINT wt_media_file_pkey PRIMARY KEY (id);


--
-- Name: wt_media wt_media_m_id_m_file_unique; Type: CONSTRAINT; Schema: public; Owner: webtrees
--

ALTER TABLE ONLY public.wt_media
    ADD CONSTRAINT wt_media_m_id_m_file_unique UNIQUE (m_id, m_file);


--
-- Name: wt_media wt_media_pkey; Type: CONSTRAINT; Schema: public; Owner: webtrees
--

ALTER TABLE ONLY public.wt_media
    ADD CONSTRAINT wt_media_pkey PRIMARY KEY (m_file, m_id);


--
-- Name: wt_message wt_message_pkey; Type: CONSTRAINT; Schema: public; Owner: webtrees
--

ALTER TABLE ONLY public.wt_message
    ADD CONSTRAINT wt_message_pkey PRIMARY KEY (message_id);


--
-- Name: wt_module wt_module_pkey; Type: CONSTRAINT; Schema: public; Owner: webtrees
--

ALTER TABLE ONLY public.wt_module
    ADD CONSTRAINT wt_module_pkey PRIMARY KEY (module_name);


--
-- Name: wt_module_privacy wt_module_privacy_ix1; Type: CONSTRAINT; Schema: public; Owner: webtrees
--

ALTER TABLE ONLY public.wt_module_privacy
    ADD CONSTRAINT wt_module_privacy_ix1 UNIQUE (gedcom_id, module_name, interface);


--
-- Name: wt_module_privacy wt_module_privacy_ix2; Type: CONSTRAINT; Schema: public; Owner: webtrees
--

ALTER TABLE ONLY public.wt_module_privacy
    ADD CONSTRAINT wt_module_privacy_ix2 UNIQUE (module_name, gedcom_id, interface);


--
-- Name: wt_module_privacy wt_module_privacy_pkey; Type: CONSTRAINT; Schema: public; Owner: webtrees
--

ALTER TABLE ONLY public.wt_module_privacy
    ADD CONSTRAINT wt_module_privacy_pkey PRIMARY KEY (id);


--
-- Name: wt_module_setting wt_module_setting_pkey; Type: CONSTRAINT; Schema: public; Owner: webtrees
--

ALTER TABLE ONLY public.wt_module_setting
    ADD CONSTRAINT wt_module_setting_pkey PRIMARY KEY (module_name, setting_name);


--
-- Name: wt_name wt_name_pkey; Type: CONSTRAINT; Schema: public; Owner: webtrees
--

ALTER TABLE ONLY public.wt_name
    ADD CONSTRAINT wt_name_pkey PRIMARY KEY (n_id, n_file, n_num);


--
-- Name: wt_news wt_news_pkey; Type: CONSTRAINT; Schema: public; Owner: webtrees
--

ALTER TABLE ONLY public.wt_news
    ADD CONSTRAINT wt_news_pkey PRIMARY KEY (news_id);


--
-- Name: wt_other wt_other_o_file_o_id_unique; Type: CONSTRAINT; Schema: public; Owner: webtrees
--

ALTER TABLE ONLY public.wt_other
    ADD CONSTRAINT wt_other_o_file_o_id_unique UNIQUE (o_file, o_id);


--
-- Name: wt_other wt_other_pkey; Type: CONSTRAINT; Schema: public; Owner: webtrees
--

ALTER TABLE ONLY public.wt_other
    ADD CONSTRAINT wt_other_pkey PRIMARY KEY (o_id, o_file);


--
-- Name: wt_place_location wt_place_location_parent_id_place_unique; Type: CONSTRAINT; Schema: public; Owner: webtrees
--

ALTER TABLE ONLY public.wt_place_location
    ADD CONSTRAINT wt_place_location_parent_id_place_unique UNIQUE (parent_id, place);


--
-- Name: wt_place_location wt_place_location_pkey; Type: CONSTRAINT; Schema: public; Owner: webtrees
--

ALTER TABLE ONLY public.wt_place_location
    ADD CONSTRAINT wt_place_location_pkey PRIMARY KEY (id);


--
-- Name: wt_place_location wt_place_location_place_parent_id_unique; Type: CONSTRAINT; Schema: public; Owner: webtrees
--

ALTER TABLE ONLY public.wt_place_location
    ADD CONSTRAINT wt_place_location_place_parent_id_unique UNIQUE (place, parent_id);


--
-- Name: wt_placelinks wt_placelinks_pkey; Type: CONSTRAINT; Schema: public; Owner: webtrees
--

ALTER TABLE ONLY public.wt_placelinks
    ADD CONSTRAINT wt_placelinks_pkey PRIMARY KEY (pl_p_id, pl_gid, pl_file);


--
-- Name: wt_places wt_places_p_parent_id_p_file_p_place_unique; Type: CONSTRAINT; Schema: public; Owner: webtrees
--

ALTER TABLE ONLY public.wt_places
    ADD CONSTRAINT wt_places_p_parent_id_p_file_p_place_unique UNIQUE (p_parent_id, p_file, p_place);


--
-- Name: wt_places wt_places_pkey; Type: CONSTRAINT; Schema: public; Owner: webtrees
--

ALTER TABLE ONLY public.wt_places
    ADD CONSTRAINT wt_places_pkey PRIMARY KEY (p_id);


--
-- Name: wt_session wt_session_pkey; Type: CONSTRAINT; Schema: public; Owner: webtrees
--

ALTER TABLE ONLY public.wt_session
    ADD CONSTRAINT wt_session_pkey PRIMARY KEY (session_id);


--
-- Name: wt_site_setting wt_site_setting_pkey; Type: CONSTRAINT; Schema: public; Owner: webtrees
--

ALTER TABLE ONLY public.wt_site_setting
    ADD CONSTRAINT wt_site_setting_pkey PRIMARY KEY (setting_name);


--
-- Name: wt_sources wt_sources_pkey; Type: CONSTRAINT; Schema: public; Owner: webtrees
--

ALTER TABLE ONLY public.wt_sources
    ADD CONSTRAINT wt_sources_pkey PRIMARY KEY (s_id, s_file);


--
-- Name: wt_sources wt_sources_s_file_s_id_unique; Type: CONSTRAINT; Schema: public; Owner: webtrees
--

ALTER TABLE ONLY public.wt_sources
    ADD CONSTRAINT wt_sources_s_file_s_id_unique UNIQUE (s_file, s_id);


--
-- Name: wt_user wt_user_email_unique; Type: CONSTRAINT; Schema: public; Owner: webtrees
--

ALTER TABLE ONLY public.wt_user
    ADD CONSTRAINT wt_user_email_unique UNIQUE (email);


--
-- Name: wt_user_gedcom_setting wt_user_gedcom_setting_pkey; Type: CONSTRAINT; Schema: public; Owner: webtrees
--

ALTER TABLE ONLY public.wt_user_gedcom_setting
    ADD CONSTRAINT wt_user_gedcom_setting_pkey PRIMARY KEY (user_id, gedcom_id, setting_name);


--
-- Name: wt_user wt_user_pkey; Type: CONSTRAINT; Schema: public; Owner: webtrees
--

ALTER TABLE ONLY public.wt_user
    ADD CONSTRAINT wt_user_pkey PRIMARY KEY (user_id);


--
-- Name: wt_user_setting wt_user_setting_pkey; Type: CONSTRAINT; Schema: public; Owner: webtrees
--

ALTER TABLE ONLY public.wt_user_setting
    ADD CONSTRAINT wt_user_setting_pkey PRIMARY KEY (user_id, setting_name);


--
-- Name: wt_user wt_user_user_name_unique; Type: CONSTRAINT; Schema: public; Owner: webtrees
--

ALTER TABLE ONLY public.wt_user
    ADD CONSTRAINT wt_user_user_name_unique UNIQUE (user_name);


--
-- Name: wt_block_gedcom_id_index; Type: INDEX; Schema: public; Owner: webtrees
--

CREATE INDEX wt_block_gedcom_id_index ON public.wt_block USING btree (gedcom_id);


--
-- Name: wt_block_module_name_index; Type: INDEX; Schema: public; Owner: webtrees
--

CREATE INDEX wt_block_module_name_index ON public.wt_block USING btree (module_name);


--
-- Name: wt_block_user_id_index; Type: INDEX; Schema: public; Owner: webtrees
--

CREATE INDEX wt_block_user_id_index ON public.wt_block USING btree (user_id);


--
-- Name: wt_change_gedcom_id_status_xref_index; Type: INDEX; Schema: public; Owner: webtrees
--

CREATE INDEX wt_change_gedcom_id_status_xref_index ON public.wt_change USING btree (gedcom_id, status, xref);


--
-- Name: wt_change_user_id_index; Type: INDEX; Schema: public; Owner: webtrees
--

CREATE INDEX wt_change_user_id_index ON public.wt_change USING btree (user_id);


--
-- Name: wt_dates_d_day_index; Type: INDEX; Schema: public; Owner: webtrees
--

CREATE INDEX wt_dates_d_day_index ON public.wt_dates USING btree (d_day);


--
-- Name: wt_dates_d_fact_d_gid_index; Type: INDEX; Schema: public; Owner: webtrees
--

CREATE INDEX wt_dates_d_fact_d_gid_index ON public.wt_dates USING btree (d_fact, d_gid);


--
-- Name: wt_dates_d_file_index; Type: INDEX; Schema: public; Owner: webtrees
--

CREATE INDEX wt_dates_d_file_index ON public.wt_dates USING btree (d_file);


--
-- Name: wt_dates_d_gid_index; Type: INDEX; Schema: public; Owner: webtrees
--

CREATE INDEX wt_dates_d_gid_index ON public.wt_dates USING btree (d_gid);


--
-- Name: wt_dates_d_julianday1_index; Type: INDEX; Schema: public; Owner: webtrees
--

CREATE INDEX wt_dates_d_julianday1_index ON public.wt_dates USING btree (d_julianday1);


--
-- Name: wt_dates_d_julianday2_index; Type: INDEX; Schema: public; Owner: webtrees
--

CREATE INDEX wt_dates_d_julianday2_index ON public.wt_dates USING btree (d_julianday2);


--
-- Name: wt_dates_d_mon_index; Type: INDEX; Schema: public; Owner: webtrees
--

CREATE INDEX wt_dates_d_mon_index ON public.wt_dates USING btree (d_mon);


--
-- Name: wt_dates_d_month_index; Type: INDEX; Schema: public; Owner: webtrees
--

CREATE INDEX wt_dates_d_month_index ON public.wt_dates USING btree (d_month);


--
-- Name: wt_dates_d_type_index; Type: INDEX; Schema: public; Owner: webtrees
--

CREATE INDEX wt_dates_d_type_index ON public.wt_dates USING btree (d_type);


--
-- Name: wt_dates_d_year_index; Type: INDEX; Schema: public; Owner: webtrees
--

CREATE INDEX wt_dates_d_year_index ON public.wt_dates USING btree (d_year);


--
-- Name: wt_families_f_husb_index; Type: INDEX; Schema: public; Owner: webtrees
--

CREATE INDEX wt_families_f_husb_index ON public.wt_families USING btree (f_husb);


--
-- Name: wt_families_f_wife_index; Type: INDEX; Schema: public; Owner: webtrees
--

CREATE INDEX wt_families_f_wife_index ON public.wt_families USING btree (f_wife);


--
-- Name: wt_favorite_gedcom_id_user_id_index; Type: INDEX; Schema: public; Owner: webtrees
--

CREATE INDEX wt_favorite_gedcom_id_user_id_index ON public.wt_favorite USING btree (gedcom_id, user_id);


--
-- Name: wt_favorite_user_id_index; Type: INDEX; Schema: public; Owner: webtrees
--

CREATE INDEX wt_favorite_user_id_index ON public.wt_favorite USING btree (user_id);


--
-- Name: wt_gedcom_chunk_gedcom_id_imported_index; Type: INDEX; Schema: public; Owner: webtrees
--

CREATE INDEX wt_gedcom_chunk_gedcom_id_imported_index ON public.wt_gedcom_chunk USING btree (gedcom_id, imported);


--
-- Name: wt_gedcom_sort_order_index; Type: INDEX; Schema: public; Owner: webtrees
--

CREATE INDEX wt_gedcom_sort_order_index ON public.wt_gedcom USING btree (sort_order);


--
-- Name: wt_log_gedcom_id_index; Type: INDEX; Schema: public; Owner: webtrees
--

CREATE INDEX wt_log_gedcom_id_index ON public.wt_log USING btree (gedcom_id);


--
-- Name: wt_log_ip_address_index; Type: INDEX; Schema: public; Owner: webtrees
--

CREATE INDEX wt_log_ip_address_index ON public.wt_log USING btree (ip_address);


--
-- Name: wt_log_log_time_index; Type: INDEX; Schema: public; Owner: webtrees
--

CREATE INDEX wt_log_log_time_index ON public.wt_log USING btree (log_time);


--
-- Name: wt_log_log_type_index; Type: INDEX; Schema: public; Owner: webtrees
--

CREATE INDEX wt_log_log_type_index ON public.wt_log USING btree (log_type);


--
-- Name: wt_log_user_id_index; Type: INDEX; Schema: public; Owner: webtrees
--

CREATE INDEX wt_log_user_id_index ON public.wt_log USING btree (user_id);


--
-- Name: wt_media_file_m_file_descriptive_title_index; Type: INDEX; Schema: public; Owner: webtrees
--

CREATE INDEX wt_media_file_m_file_descriptive_title_index ON public.wt_media_file USING btree (m_file, descriptive_title);


--
-- Name: wt_media_file_m_file_m_id_index; Type: INDEX; Schema: public; Owner: webtrees
--

CREATE INDEX wt_media_file_m_file_m_id_index ON public.wt_media_file USING btree (m_file, m_id);


--
-- Name: wt_media_file_m_file_multimedia_file_refn_index; Type: INDEX; Schema: public; Owner: webtrees
--

CREATE INDEX wt_media_file_m_file_multimedia_file_refn_index ON public.wt_media_file USING btree (m_file, multimedia_file_refn);


--
-- Name: wt_media_file_m_file_multimedia_format_index; Type: INDEX; Schema: public; Owner: webtrees
--

CREATE INDEX wt_media_file_m_file_multimedia_format_index ON public.wt_media_file USING btree (m_file, multimedia_format);


--
-- Name: wt_media_file_m_file_source_media_type_index; Type: INDEX; Schema: public; Owner: webtrees
--

CREATE INDEX wt_media_file_m_file_source_media_type_index ON public.wt_media_file USING btree (m_file, source_media_type);


--
-- Name: wt_media_file_m_id_m_file_index; Type: INDEX; Schema: public; Owner: webtrees
--

CREATE INDEX wt_media_file_m_id_m_file_index ON public.wt_media_file USING btree (m_id, m_file);


--
-- Name: wt_message_user_id_index; Type: INDEX; Schema: public; Owner: webtrees
--

CREATE INDEX wt_message_user_id_index ON public.wt_message USING btree (user_id);


--
-- Name: wt_name_n_full_n_id_n_file_index; Type: INDEX; Schema: public; Owner: webtrees
--

CREATE INDEX wt_name_n_full_n_id_n_file_index ON public.wt_name USING btree (n_full, n_id, n_file);


--
-- Name: wt_name_n_givn_n_file_n_type_n_id_index; Type: INDEX; Schema: public; Owner: webtrees
--

CREATE INDEX wt_name_n_givn_n_file_n_type_n_id_index ON public.wt_name USING btree (n_givn, n_file, n_type, n_id);


--
-- Name: wt_name_n_surn_n_file_n_type_n_id_index; Type: INDEX; Schema: public; Owner: webtrees
--

CREATE INDEX wt_name_n_surn_n_file_n_type_n_id_index ON public.wt_name USING btree (n_surn, n_file, n_type, n_id);


--
-- Name: wt_news_gedcom_id_updated_index; Type: INDEX; Schema: public; Owner: webtrees
--

CREATE INDEX wt_news_gedcom_id_updated_index ON public.wt_news USING btree (gedcom_id, updated);


--
-- Name: wt_news_user_id_updated_index; Type: INDEX; Schema: public; Owner: webtrees
--

CREATE INDEX wt_news_user_id_updated_index ON public.wt_news USING btree (user_id, updated);


--
-- Name: wt_place_location_latitude_index; Type: INDEX; Schema: public; Owner: webtrees
--

CREATE INDEX wt_place_location_latitude_index ON public.wt_place_location USING btree (latitude);


--
-- Name: wt_place_location_longitude_index; Type: INDEX; Schema: public; Owner: webtrees
--

CREATE INDEX wt_place_location_longitude_index ON public.wt_place_location USING btree (longitude);


--
-- Name: wt_placelinks_pl_file_index; Type: INDEX; Schema: public; Owner: webtrees
--

CREATE INDEX wt_placelinks_pl_file_index ON public.wt_placelinks USING btree (pl_file);


--
-- Name: wt_placelinks_pl_gid_index; Type: INDEX; Schema: public; Owner: webtrees
--

CREATE INDEX wt_placelinks_pl_gid_index ON public.wt_placelinks USING btree (pl_gid);


--
-- Name: wt_placelinks_pl_p_id_index; Type: INDEX; Schema: public; Owner: webtrees
--

CREATE INDEX wt_placelinks_pl_p_id_index ON public.wt_placelinks USING btree (pl_p_id);


--
-- Name: wt_places_p_file_p_place_index; Type: INDEX; Schema: public; Owner: webtrees
--

CREATE INDEX wt_places_p_file_p_place_index ON public.wt_places USING btree (p_file, p_place);


--
-- Name: wt_session_session_time_index; Type: INDEX; Schema: public; Owner: webtrees
--

CREATE INDEX wt_session_session_time_index ON public.wt_session USING btree (session_time);


--
-- Name: wt_session_user_id_ip_address_index; Type: INDEX; Schema: public; Owner: webtrees
--

CREATE INDEX wt_session_user_id_ip_address_index ON public.wt_session USING btree (user_id, ip_address);


--
-- Name: wt_sources_s_name_index; Type: INDEX; Schema: public; Owner: webtrees
--

CREATE INDEX wt_sources_s_name_index ON public.wt_sources USING btree (s_name);


--
-- Name: wt_user_gedcom_setting_gedcom_id_index; Type: INDEX; Schema: public; Owner: webtrees
--

CREATE INDEX wt_user_gedcom_setting_gedcom_id_index ON public.wt_user_gedcom_setting USING btree (gedcom_id);


--
-- Name: wt_block wt_block_gedcom_id_foreign; Type: FK CONSTRAINT; Schema: public; Owner: webtrees
--

ALTER TABLE ONLY public.wt_block
    ADD CONSTRAINT wt_block_gedcom_id_foreign FOREIGN KEY (gedcom_id) REFERENCES public.wt_gedcom(gedcom_id);


--
-- Name: wt_block wt_block_module_name_foreign; Type: FK CONSTRAINT; Schema: public; Owner: webtrees
--

ALTER TABLE ONLY public.wt_block
    ADD CONSTRAINT wt_block_module_name_foreign FOREIGN KEY (module_name) REFERENCES public.wt_module(module_name);


--
-- Name: wt_block_setting wt_block_setting_block_id_foreign; Type: FK CONSTRAINT; Schema: public; Owner: webtrees
--

ALTER TABLE ONLY public.wt_block_setting
    ADD CONSTRAINT wt_block_setting_block_id_foreign FOREIGN KEY (block_id) REFERENCES public.wt_block(block_id);


--
-- Name: wt_block wt_block_user_id_foreign; Type: FK CONSTRAINT; Schema: public; Owner: webtrees
--

ALTER TABLE ONLY public.wt_block
    ADD CONSTRAINT wt_block_user_id_foreign FOREIGN KEY (user_id) REFERENCES public.wt_user(user_id);


--
-- Name: wt_change wt_change_gedcom_id_foreign; Type: FK CONSTRAINT; Schema: public; Owner: webtrees
--

ALTER TABLE ONLY public.wt_change
    ADD CONSTRAINT wt_change_gedcom_id_foreign FOREIGN KEY (gedcom_id) REFERENCES public.wt_gedcom(gedcom_id);


--
-- Name: wt_change wt_change_user_id_foreign; Type: FK CONSTRAINT; Schema: public; Owner: webtrees
--

ALTER TABLE ONLY public.wt_change
    ADD CONSTRAINT wt_change_user_id_foreign FOREIGN KEY (user_id) REFERENCES public.wt_user(user_id);


--
-- Name: wt_default_resn wt_default_resn_gedcom_id_foreign; Type: FK CONSTRAINT; Schema: public; Owner: webtrees
--

ALTER TABLE ONLY public.wt_default_resn
    ADD CONSTRAINT wt_default_resn_gedcom_id_foreign FOREIGN KEY (gedcom_id) REFERENCES public.wt_gedcom(gedcom_id);


--
-- Name: wt_favorite wt_favorite_gedcom_id_foreign; Type: FK CONSTRAINT; Schema: public; Owner: webtrees
--

ALTER TABLE ONLY public.wt_favorite
    ADD CONSTRAINT wt_favorite_gedcom_id_foreign FOREIGN KEY (gedcom_id) REFERENCES public.wt_gedcom(gedcom_id) ON DELETE CASCADE;


--
-- Name: wt_favorite wt_favorite_user_id_foreign; Type: FK CONSTRAINT; Schema: public; Owner: webtrees
--

ALTER TABLE ONLY public.wt_favorite
    ADD CONSTRAINT wt_favorite_user_id_foreign FOREIGN KEY (user_id) REFERENCES public.wt_user(user_id) ON DELETE CASCADE;


--
-- Name: wt_gedcom_chunk wt_gedcom_chunk_gedcom_id_foreign; Type: FK CONSTRAINT; Schema: public; Owner: webtrees
--

ALTER TABLE ONLY public.wt_gedcom_chunk
    ADD CONSTRAINT wt_gedcom_chunk_gedcom_id_foreign FOREIGN KEY (gedcom_id) REFERENCES public.wt_gedcom(gedcom_id);


--
-- Name: wt_gedcom_setting wt_gedcom_setting_gedcom_id_foreign; Type: FK CONSTRAINT; Schema: public; Owner: webtrees
--

ALTER TABLE ONLY public.wt_gedcom_setting
    ADD CONSTRAINT wt_gedcom_setting_gedcom_id_foreign FOREIGN KEY (gedcom_id) REFERENCES public.wt_gedcom(gedcom_id);


--
-- Name: wt_hit_counter wt_hit_counter_gedcom_id_foreign; Type: FK CONSTRAINT; Schema: public; Owner: webtrees
--

ALTER TABLE ONLY public.wt_hit_counter
    ADD CONSTRAINT wt_hit_counter_gedcom_id_foreign FOREIGN KEY (gedcom_id) REFERENCES public.wt_gedcom(gedcom_id);


--
-- Name: wt_log wt_log_gedcom_id_foreign; Type: FK CONSTRAINT; Schema: public; Owner: webtrees
--

ALTER TABLE ONLY public.wt_log
    ADD CONSTRAINT wt_log_gedcom_id_foreign FOREIGN KEY (gedcom_id) REFERENCES public.wt_gedcom(gedcom_id);


--
-- Name: wt_log wt_log_user_id_foreign; Type: FK CONSTRAINT; Schema: public; Owner: webtrees
--

ALTER TABLE ONLY public.wt_log
    ADD CONSTRAINT wt_log_user_id_foreign FOREIGN KEY (user_id) REFERENCES public.wt_user(user_id);


--
-- Name: wt_message wt_message_user_id_foreign; Type: FK CONSTRAINT; Schema: public; Owner: webtrees
--

ALTER TABLE ONLY public.wt_message
    ADD CONSTRAINT wt_message_user_id_foreign FOREIGN KEY (user_id) REFERENCES public.wt_user(user_id);


--
-- Name: wt_module_privacy wt_module_privacy_gedcom_id_foreign; Type: FK CONSTRAINT; Schema: public; Owner: webtrees
--

ALTER TABLE ONLY public.wt_module_privacy
    ADD CONSTRAINT wt_module_privacy_gedcom_id_foreign FOREIGN KEY (gedcom_id) REFERENCES public.wt_gedcom(gedcom_id) ON DELETE CASCADE;


--
-- Name: wt_module_privacy wt_module_privacy_module_name_foreign; Type: FK CONSTRAINT; Schema: public; Owner: webtrees
--

ALTER TABLE ONLY public.wt_module_privacy
    ADD CONSTRAINT wt_module_privacy_module_name_foreign FOREIGN KEY (module_name) REFERENCES public.wt_module(module_name) ON DELETE CASCADE;


--
-- Name: wt_module_setting wt_module_setting_module_name_foreign; Type: FK CONSTRAINT; Schema: public; Owner: webtrees
--

ALTER TABLE ONLY public.wt_module_setting
    ADD CONSTRAINT wt_module_setting_module_name_foreign FOREIGN KEY (module_name) REFERENCES public.wt_module(module_name);


--
-- Name: wt_news wt_news_gedcom_id_foreign; Type: FK CONSTRAINT; Schema: public; Owner: webtrees
--

ALTER TABLE ONLY public.wt_news
    ADD CONSTRAINT wt_news_gedcom_id_foreign FOREIGN KEY (gedcom_id) REFERENCES public.wt_gedcom(gedcom_id) ON DELETE CASCADE;


--
-- Name: wt_news wt_news_user_id_foreign; Type: FK CONSTRAINT; Schema: public; Owner: webtrees
--

ALTER TABLE ONLY public.wt_news
    ADD CONSTRAINT wt_news_user_id_foreign FOREIGN KEY (user_id) REFERENCES public.wt_user(user_id) ON DELETE CASCADE;


--
-- Name: wt_place_location wt_place_location_parent_id_foreign; Type: FK CONSTRAINT; Schema: public; Owner: webtrees
--

ALTER TABLE ONLY public.wt_place_location
    ADD CONSTRAINT wt_place_location_parent_id_foreign FOREIGN KEY (parent_id) REFERENCES public.wt_place_location(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: wt_user_gedcom_setting wt_user_gedcom_setting_gedcom_id_foreign; Type: FK CONSTRAINT; Schema: public; Owner: webtrees
--

ALTER TABLE ONLY public.wt_user_gedcom_setting
    ADD CONSTRAINT wt_user_gedcom_setting_gedcom_id_foreign FOREIGN KEY (gedcom_id) REFERENCES public.wt_gedcom(gedcom_id);


--
-- Name: wt_user_gedcom_setting wt_user_gedcom_setting_user_id_foreign; Type: FK CONSTRAINT; Schema: public; Owner: webtrees
--

ALTER TABLE ONLY public.wt_user_gedcom_setting
    ADD CONSTRAINT wt_user_gedcom_setting_user_id_foreign FOREIGN KEY (user_id) REFERENCES public.wt_user(user_id);


--
-- Name: wt_user_setting wt_user_setting_user_id_foreign; Type: FK CONSTRAINT; Schema: public; Owner: webtrees
--

ALTER TABLE ONLY public.wt_user_setting
    ADD CONSTRAINT wt_user_setting_user_id_foreign FOREIGN KEY (user_id) REFERENCES public.wt_user(user_id);


--
-- PostgreSQL database dump complete
--


