name: "Build Webtrees"

on:
  push:
    branches:
      - "*"
#      - master
#    tags:
#      - v*
  pull_request:
    branches:
    - master
#  schedule:
#    -cron: '0 0 * * 0' # weekly
  workflow_dispatch:
    branches:
      - "*"

jobs:
  build:
    env:
      QEMU_VERSION: "v5.1.0-7"
      WT_VERSION: "2.0.11"
      DOCKER_FILE: Dockerfile.github
      COMMIT_SHA: ${{ github.sha }}

    runs-on: ubuntu-20.04
    strategy:
      matrix:
       include:
        - arch: "amd64"
          qemu-arch: "x86_64"
        - arch: "arm32v7"
          qemu-arch: "arm"
        - arch: "arm64v8"
          qemu-arch: "aarch64"
        - arch: "ppc64le"
          qemu-arch: "ppc64le"
        - arch: "s390x"
          qemu-arch: "s390x"

    steps:
      - uses: actions/checkout@v2
      - name: Preparation 
        id: prep
        run: |
          echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
          echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
          echo ::set-output name=TARGET::dtjs48jkt/webtrees-dev
          echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
          echo ::set-output name=BUILD_VERSION::${SHORT_SHA}
          echo ::set-output name=BUILD_DATE::$(date -u +'%Y-%m-%dT%H:%M:%SZ')
          if [[ "${{ steps.prep.outputs.SOURCE_TAG }}" =~ ^v[0-9\.-]*$ ]]; then
            echo ::set-output name=TARGET::dtjs48jkt/webtrees
            echo ::set-output name=BUILD_VERSION::${{ steps.prep.outputs.SOURCE_TAG }}
          fi
          chmod 775 docker.sh
          ./docker.sh prepare
      - name: "Build Docker Image"
        env:
          ARCH: ${{ matrix.arch }}
          QEMU_ARCH: ${{ matrix.qemu-arch }}
          BUILD_VERSION: ${{ steps.prep.outputs.VERSION }}
          BUILD_DATE: ${{ steps.prep.outputs.BUILD_DATE }}
          BUILD_REF: ${{ env.COMMIT_SHA }}
          TARGET: ${{ steps.prep.outputs.TARGET }}
        run: |
          echo "BUILD_VERSION: $BUILD_VERSION"
          echo BUILD_DATE: $BUILD_DATE
          echo BUILD_REF: $BUILD_REF
          echo TARGET: ${{ env.TARGET }}
          echo COMMIT_SHA: ${{ env.COMMIT_SHA }}
          ./docker.sh build
      - name: "Test Docker Image"
        run: ./docker.sh test
#      - name: "Push Docker Image"
#        run: ./docker.sh tag && echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin && ./docker.sh push && docker logout
#        if: env.str == 'ABC' && env.num == 123 # only when tag is set

#  manifest:
#    needs: build
#    runs-on: ubuntu-latest
